"""drop squad_players (team-based first scorer)

Revision ID: b0be15a80128
Revises: edbcfec84e20
Create Date: 2026-06-15 15:06:26.307640
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0be15a80128"
down_revision: str | None = "edbcfec84e20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("squad_players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_squad_players_team_id"))

    op.drop_table("squad_players")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "squad_players",
        sa.Column("player_id", sa.INTEGER(), nullable=False),
        sa.Column("team_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("position", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("player_id"),
    )
    with op.batch_alter_table("squad_players", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_squad_players_team_id"), ["team_id"], unique=False)

    # ### end Alembic commands ###
