"""initial schema

Revision ID: edbcfec84e20
Revises:
Create Date: 2026-06-15 12:04:11.830188
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edbcfec84e20"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("budget_date", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("budget_date"),
    )
    op.create_table(
        "games",
        sa.Column("fixture_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("match_hash", sa.String(), nullable=False),
        sa.Column("stage", sa.Enum("GROUP", "KNOCKOUT", name="stage"), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("home_team_name", sa.String(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_name", sa.String(), nullable=False),
        sa.Column("kickoff_utc", sa.DateTime(), nullable=False),
        sa.Column("kickoff_local", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "LIVE",
                "FINISHED",
                "POSTPONED",
                "CANCELLED",
                "VOID",
                name="game_status",
            ),
            nullable=False,
        ),
        sa.Column("home_goals_90", sa.Integer(), nullable=True),
        sa.Column("away_goals_90", sa.Integer(), nullable=True),
        sa.Column("advancing_team_id", sa.Integer(), nullable=True),
        sa.Column("first_scorer_player_id", sa.Integer(), nullable=True),
        sa.Column("announced_at", sa.DateTime(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("fixture_id"),
    )
    op.create_table(
        "players",
        sa.Column("telegram_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "squad_players",
        sa.Column("player_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("player_id"),
    )
    with op.batch_alter_table("squad_players", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_squad_players_team_id"), ["team_id"], unique=False)

    op.create_table(
        "bets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("player_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("payload_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("points_awarded", sa.Integer(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["games.fixture_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_telegram_id"],
            ["players.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_id", "player_telegram_id", "category", name="uq_bet_one_per_category"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bets")
    with op.batch_alter_table("squad_players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_squad_players_team_id"))

    op.drop_table("squad_players")
    op.drop_table("players")
    op.drop_table("games")
    op.drop_table("api_usage")
    # ### end Alembic commands ###
